# Generated by Django 4.0 on 2022-02-02 10:39

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('core', '0001_initial'),
        ('map', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Container',
            fields=[
                ('defaultobject_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='core.defaultobject')),
            ],
            options={
                'verbose_name': 'Container',
                'verbose_name_plural': 'Containers',
            },
            bases=('core.defaultobject', models.Model),
        ),
        migrations.CreateModel(
            name='ContainerItemType',
            fields=[
                ('defaultobject_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='core.defaultobject')),
                ('icon', models.ImageField(blank=True, upload_to='uploads/icons/containeritemtype', verbose_name='icon')),
            ],
            options={
                'verbose_name': 'ContainerItemType',
                'verbose_name_plural': 'ContainerItemTypes',
            },
            bases=('core.defaultobject', models.Model),
        ),
        migrations.CreateModel(
            name='ContainerType',
            fields=[
                ('defaultobject_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='core.defaultobject')),
                ('icon', models.ImageField(blank=True, upload_to='uploads/icons/container', verbose_name='icon')),
            ],
            options={
                'verbose_name': 'Containertype',
                'verbose_name_plural': 'Containertypes',
            },
            bases=('core.defaultobject', models.Model),
        ),
        migrations.CreateModel(
            name='ContainerLocation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('level', models.IntegerField(verbose_name='level')),
                ('position', models.IntegerField(verbose_name='position')),
                ('depth', models.IntegerField(default=0, verbose_name='depth')),
                ('location_barcode', models.CharField(blank=True, max_length=70, verbose_name='location_barcode')),
                ('qrcode', models.ImageField(blank=True, upload_to='uploads/barcodes/containerlocations', verbose_name='qrcode')),
                ('container_fk', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='room_equipment.container', verbose_name='container')),
            ],
            options={
                'verbose_name': 'containerlocation',
                'verbose_name_plural': 'containerlocations',
            },
        ),
        migrations.CreateModel(
            name='ContainerItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('description', models.TextField(blank=True, verbose_name='description')),
                ('container_item_type_fk', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='room_equipment.containeritemtype', verbose_name='container_item_type')),
                ('container_location_fk', models.ForeignKey(help_text='This indicates location in container', null=True, on_delete=django.db.models.deletion.CASCADE, to='room_equipment.containerlocation', verbose_name='container_location')),
            ],
            options={
                'verbose_name': 'ContainerItem',
                'verbose_name_plural': 'ContainerItems',
            },
        ),
        migrations.CreateModel(
            name='ContainerFieldLocation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('description', models.TextField(blank=True, verbose_name='description')),
                ('container_fk', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='room_equipment.container', verbose_name='container')),
                ('field_fk', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='map.field', verbose_name='field')),
            ],
            options={
                'verbose_name': 'ContainerFieldLocation',
                'verbose_name_plural': 'ContainerFieldLocations',
            },
        ),
        migrations.AddField(
            model_name='container',
            name='container_type_fk',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='room_equipment.containertype', verbose_name='container_type'),
        ),
    ]
