# Generated by Django 4.0 on 2022-02-02 14:51

from django.db import migrations, models
import django.db.models.deletion
import room_equipment.models


class Migration(migrations.Migration):

    dependencies = [
        ('room_equipment', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='containerlocation',
            name='container_fk',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='room_equipment.container', validators=[room_equipment.models.validate_container_fk], verbose_name='container'),
        ),
    ]
