# Generated by Django 4.0 on 2022-01-13 22:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('stock', '0003_remove_item_location_fk'),
        ('room_equipment', '0007_locationtype_location'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='location',
            name='container_level_fk',
        ),
        migrations.RemoveField(
            model_name='location',
            name='defaultobject_ptr',
        ),
        migrations.RemoveField(
            model_name='location',
            name='location_type',
        ),
        migrations.RemoveField(
            model_name='locationtype',
            name='defaultobject_ptr',
        ),
        migrations.DeleteModel(
            name='ContainerLevel',
        ),
        migrations.DeleteModel(
            name='Location',
        ),
        migrations.DeleteModel(
            name='LocationType',
        ),
    ]
