# Generated by Django 4.0 on 2022-01-13 22:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('room_equipment', '0008_remove_location_container_level_fk_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='containertype',
            name='icon',
            field=models.ImageField(blank=True, upload_to='uploads/container/icons', verbose_name='icon'),
        ),
    ]
