# Generated by Django 4.0 on 2022-01-13 23:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
        ('room_equipment', '0011_unitcontainer'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='UnitContainer',
            new_name='ItemLocationType',
        ),
    ]
