# Generated by Django 4.0 on 2022-01-13 23:48

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
        ('room_equipment', '0012_rename_unitcontainer_itemlocationtype'),
    ]

    operations = [
        migrations.CreateModel(
            name='ContainerItemType',
            fields=[
                ('defaultobject_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='core.defaultobject')),
            ],
            options={
                'verbose_name': 'ContainerItemType',
                'verbose_name_plural': 'ContainerItemTypes',
            },
            bases=('core.defaultobject', models.Model),
        ),
        migrations.CreateModel(
            name='ContainerItem',
            fields=[
                ('defaultobject_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='core.defaultobject')),
                ('position', models.IntegerField(verbose_name='position')),
                ('level', models.IntegerField(default=0, verbose_name='level')),
                ('depth', models.IntegerField(default=0, verbose_name='depth')),
                ('container_fk', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='room_equipment.container', verbose_name='container')),
            ],
            options={
                'verbose_name': 'ContainerItem',
                'verbose_name_plural': 'ContainerItems',
            },
            bases=('core.defaultobject', models.Model),
        ),
    ]
