# Generated by Django 4.0 on 2022-01-13 23:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('room_equipment', '0015_containeritem'),
    ]

    operations = [
        migrations.DeleteModel(
            name='ItemLocationType',
        ),
    ]
