# Generated by Django 4.0 on 2022-01-23 18:51

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('stock', '0003_remove_item_location_fk'),
        ('core', '0001_initial'),
        ('room_equipment', '0016_delete_itemlocationtype'),
    ]

    operations = [
        migrations.CreateModel(
            name='ItemLocation',
            fields=[
                ('defaultobject_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='core.defaultobject')),
                ('pieces', models.IntegerField(verbose_name='pieces')),
                ('container_fk', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='room_equipment.containeritem', verbose_name='container_item')),
                ('item_fk', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='stock.item', verbose_name='item')),
            ],
            options={
                'verbose_name': 'ItemLocation',
                'verbose_name_plural': 'ItemLocations',
            },
            bases=('core.defaultobject', models.Model),
        ),
    ]
