# Generated by Django 4.0 on 2022-01-23 18:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('room_equipment', '0017_itemlocation'),
    ]

    operations = [
        migrations.DeleteModel(
            name='ItemLocation',
        ),
    ]
