# Generated by Django 4.0 on 2022-01-23 22:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('map', '0007_remove_field_container_fk'),
        ('room_equipment', '0020_container_area_fk'),
    ]

    operations = [
        migrations.AlterField(
            model_name='container',
            name='fields',
            field=models.ManyToManyField(blank=True, to='map.Field', verbose_name='fields'),
        ),
    ]
