# Generated by Django 4.0 on 2022-01-23 22:56

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('map', '0007_remove_field_container_fk'),
        ('room_equipment', '0021_alter_container_fields'),
    ]

    operations = [
        migrations.CreateModel(
            name='ContainerLocation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('description', models.TextField(verbose_name='description')),
                ('container_fk', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='room_equipment.container', verbose_name='container')),
                ('field_fk', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='map.field', verbose_name='field')),
            ],
            options={
                'verbose_name': 'ContainerLocation',
                'verbose_name_plural': 'ContainerLocations',
            },
        ),
    ]
