# Generated by Django 4.0 on 2022-01-23 22:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('room_equipment', '0022_containerlocation'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='container',
            name='area_fk',
        ),
        migrations.RemoveField(
            model_name='container',
            name='fields',
        ),
    ]
