# Generated by Django 4.0 on 2022-01-23 23:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('room_equipment', '0023_remove_container_area_fk_remove_container_fields'),
    ]

    operations = [
        migrations.AlterField(
            model_name='containerlocation',
            name='description',
            field=models.TextField(blank=True, verbose_name='description'),
        ),
    ]
