# Generated by Django 4.0 on 2022-01-13 22:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('stock', '0002_alter_item_location_fk'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='item',
            name='location_fk',
        ),
    ]
