# Generated by Django 4.0 on 2022-01-23 19:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('stock', '0004_itemlocation'),
    ]

    operations = [
        migrations.DeleteModel(
            name='ItemLocation',
        ),
    ]
