# Generated by Django 4.0 on 2022-01-23 19:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stock', '0006_itemlocation'),
    ]

    operations = [
        migrations.AddField(
            model_name='item',
            name='serial',
            field=models.CharField(blank=True, max_length=70, verbose_name='serial'),
        ),
    ]
