# Generated by Django 4.0 on 2022-01-23 21:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('stock', '0007_item_serial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='itemlocation',
            old_name='container_fk',
            new_name='container_item_fk',
        ),
    ]
