# Generated by Django 4.0 on 2022-01-14 00:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('map', '0003_alter_field_container_fk'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='field',
            name='x',
        ),
        migrations.RemoveField(
            model_name='field',
            name='y',
        ),
        migrations.AddField(
            model_name='field',
            name='level',
            field=models.IntegerField(null=True, verbose_name='level'),
        ),
        migrations.AddField(
            model_name='field',
            name='position',
            field=models.IntegerField(null=True, verbose_name='position'),
        ),
    ]
