# Generated by Django 4.0 on 2022-01-14 01:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('map', '0005_remove_field_level_remove_field_position_field_x_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='field',
            name='x',
        ),
        migrations.RemoveField(
            model_name='field',
            name='y',
        ),
        migrations.AddField(
            model_name='field',
            name='level',
            field=models.IntegerField(null=True, verbose_name='level'),
        ),
        migrations.AddField(
            model_name='field',
            name='position',
            field=models.IntegerField(null=True, verbose_name='position'),
        ),
    ]
