# Generated by Django 4.0 on 2022-01-23 22:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('map', '0006_remove_field_x_remove_field_y_field_level_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='field',
            name='container_fk',
        ),
    ]
